# --- !Ups

create table "people" (
  "id" bigint generated by default as identity(start with 1) not null primary key,
  "name" varchar not null,
  "age" int not null
);

create table "item" (
  "id" bigint generated by default as identity(start with 1) not null primary key,
  "name" varchar not null,
  "description" varchar
);

create table "inventoryItem" (
  "id" bigint generated by default as identity(start with 1) not null primary key,
  "itemId" varchar not null,
  "formattedId" varchar not null,
  "status" varchar not null default 'AVAILABLE',
  CONSTRAINT `FK_item` FOREIGN KEY (`itemId`) REFERENCES `item` (`id`)
);

merge into item (id, name, description) KEY (id) values (1, 'Project to Product', 'Great book!');
merge into inventoryItem (id, itemId, formattedId, status) KEY (id) values (1, 1, 'p1', 'AVAILABLE');
merge into inventoryItem (id, itemId, formattedId, status) KEY (id) values (2, 1, 'p2', 'AVAILABLE');
merge into inventoryItem (id, itemId, formattedId, status) KEY (id) values (3, 1, 'p3', 'CHECKED_OUT');

merge into item (id, name, description) KEY (id) values (2, 'Clean Code', 'A must read');
merge into inventoryItem (id, itemId, formattedId, status) KEY (id) values (4, 2, '1', 'AVAILABLE');
merge into inventoryItem (id, itemId, formattedId, status) KEY (id) values (5, 2, '2', 'AVAILABLE');


# --- !Downs

drop table "people" if exists;
drop table "inventoryItem" if exists;
drop table "item" if exists;
